name: Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-msg: "Update flake.lock"
          pr-labels: |
            dependencies
            automated

      - name: Build and push niri-unstable to Cachix
        if: ${{ steps.update.outputs.pull-request-number != '' }}
        run: |
          nix-store --query --requisites $(nix-store --query --deriver $(nix build --print-out-paths .)) | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Auto merge PR
        if: ${{ steps.update.outputs.pull-request-number != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
